name: Continuous integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'

jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Deno
        uses: denoland/setup-deno@v1
      - name: Setup Velociraptor
        uses: jurassiscripts/setup-velociraptor@v1
      - name: Setup dprint
        run: curl -fsSL https://dprint.dev/install.sh | sh && cp /home/runner/.dprint/bin/dprint /usr/local/bin/dprint
      - name: Lint code
        run: vr build && vr lint
  format:
    name: Format code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Deno
        uses: denoland/setup-deno@v1
      - name: Setup Velociraptor
        uses: jurassiscripts/setup-velociraptor@v1
      - name: Setup dprint
        run: curl -fsSL https://dprint.dev/install.sh | sh && cp /home/runner/.dprint/bin/dprint /usr/local/bin/dprint
      - name: Format code
        run: vr build && vr fmt-check
  test:
    name: Test code
    runs-on: ${{ matrix.os }}
    needs:
      - lint
      - format
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Deno
        uses: denoland/setup-deno@v1
      - name: Setup Velociraptor
        uses: jurassiscripts/setup-velociraptor@v1
      - name: Setup dprint
        run: curl -fsSL https://dprint.dev/install.sh | sh && cp /home/runner/.dprint/bin/dprint /usr/local/bin/dprint
      - name: Format code
        run: vr build && vr test
  codeql:
    name: Analyze code
    runs-on: ubuntu-latest
    needs:
      - lint
      - format
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: typescript
          config-file: .github/config/codeql.yml
      - name: Analyze code
        uses: github/codeql-action/analyze@v1
